@startuml

title Open Course - Diagram

autonumber
actor Manager as M
participant "OpenCourseUI" as UI <<UI>>
participant "OpenCourseController" as Controller <<Application>>
participant "ListCourseByStateService" as Service <<Application>>
database "CourseRepository" as CRepo <<Persistence>>
participant "Course" as C <<Domain>>


activate UI
M --> UI : onLoad
UI -> Controller: findCourses()
activate Controller
Controller -> Service: findCourseByState(state)
activate Service
Service -> CRepo: findByState(state)
activate CRepo
CRepo -> Service: returns courses
deactivate CRepo
Service -> Controller: returns courses
deactivate Service
Controller -> UI: returns courses
deactivate Controller
UI --> M: display courses


M --> UI : choose course


UI -> Controller: changeCourseState(course)
activate Controller
Controller -> C : openCourse()




Controller -> CRepo: save(course)
activate CRepo
CRepo -> Controller: returns sucess
deactivate CRepo
Controller -> UI: returns sucess
deactivate Controller
UI --> M: shows sucess

@enduml
